name: Update Studies

on:
  schedule: 
  # Runs at 05:00, only on Monday. (00:00 EST)
    - cron: 0 5 * * 1

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-studies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm i --only=dev

      - name: Write current date to environment variable
        run: echo "DATE=$(date +'%Y-%m-%d-%H.%M.%S%p')" >> $GITHUB_ENV

      - name: Add git user configuration
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Fetch staging from remote
        run: |
          git fetch
          git switch testing/update-studies/staging
      
      - name: Update studies
        run: |
          echo "OUTPUT<<EOF" >> $GITHUB_ENV
          npm run update-studies >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Check for untracked files
        run: |
          git add -A
          if git status | grep -q 'Changes to be committed'; then
            echo "UPDATED=true" >> $GITHUB_ENV
            echo "${{ env.OUTPUT }}" > $GITHUB_STEP_SUMMARY
          else
            echo "No studies were updated. No changes have been made." > $GITHUB_STEP_SUMMARY
          fi
          
      # Only run the next two steps if there were changes detected by `git status` in the previous step
      - name: Commit changes and push to new branch
        if: ${{ env.UPDATED == 'true' }}
        run: |
          git commit -m "Updated studies"
          git checkout -b $(echo "testing/update-studies/update-studies-${{ env.DATE }}")
          git push -u origin $(echo "testing/update-studies/update-studies-${{ env.DATE }}")
          
      - name: Create a new pull request
        if: ${{ env.UPDATED == 'true' }}
        run: |
          gh pr create \
            --base testing/update-studies/staging \
            --head "testing/update-studies/update-studies-${{ env.DATE }}" \
            --title "Merge testing/update-studies/update-studies-${{ env.DATE }} into testing/update-studies/staging" \
            --body "${{ env.OUTPUT }}" \
            --reviewer Woozl \
            --label update-studies,autogenerated \
            >> $GITHUB_STEP_SUMMARY
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}